Backport from Electron Cash -- fix missing bitcoin: URI types form macOS Info.plist, plus support for building from a MacPorts system

diff --git a/contrib/build-osx/make_osx b/contrib/build-osx/make_osx
--- a/contrib/build-osx/make_osx
+++ b/contrib/build-osx/make_osx
@@ -15,7 +15,7 @@ cd $src_dir/../..
 export PYTHONHASHSEED=22
 VERSION=`git describe --tags --dirty`
 
-which brew > /dev/null 2>&1 || fail "Please install brew from https://brew.sh/ to continue"
+which brew > /dev/null 2>&1 || which port > /dev/null 2>&1 || fail "Please install either Homebrew (from https://brew.sh/) or MacPorts (from https://www.macports.org/) to continue"
 
 info "Installing Python $PYTHON_VERSION"
 export PATH="~/.pyenv/bin:~/.pyenv/shims:~/Library/Python/3.6/bin:$PATH"
@@ -89,6 +89,12 @@ done
 
 info "Building binary"
 pyinstaller --noconfirm --ascii --clean --name $VERSION contrib/build-osx/osx.spec || fail "Could not build binary"
+
+info "Adding bitcoin URI types to Info.plist"
+plutil -insert 'CFBundleURLTypes' \
+	-xml '<array><dict> <key>CFBundleURLName</key> <string>bitcoin</string> <key>CFBundleURLSchemes</key> <array><string>bitcoin</string></array> </dict></array>' \
+	-- dist/$PACKAGE.app/Contents/Info.plist \
+	|| fail "Could not add keys to Info.plist. Make sure the program 'plutil' exists and is installed."
 
 info "Creating .DMG"
 hdiutil create -fs HFS+ -volname $PACKAGE -srcfolder dist/$PACKAGE.app dist/electrum-$VERSION.dmg || fail "Could not create .DMG"
