Added MacPorts support to make_osx script

diff --git a/contrib/build-osx/make_osx b/contrib/build-osx/make_osx
--- a/contrib/build-osx/make_osx
+++ b/contrib/build-osx/make_osx
@@ -15,7 +15,16 @@ cd $src_dir/../..
 export PYTHONHASHSEED=22
 VERSION=`git describe --tags --dirty`
 
-which brew > /dev/null 2>&1 || fail "Please install brew from https://brew.sh/ to continue"
+uses_brew=0
+uses_ports=0
+if which brew > /dev/null 2>&1; then
+  uses_brew=1
+elif which port > /dev/null 2>&1; then
+  uses_ports=1
+  [ `port installed autoconf automake libtool | grep active | wc -l` -ge 3 ] || fail "MacPorts system detected, but required packages missing. Please run: sudo port install autoconf automake libtool"
+else
+  fail "Please install either Homebrew (from https://brew.sh/) or MacPorts (from https://www.macports.org/) to continue"
+fi
 
 info "Installing Python $PYTHON_VERSION"
 export PATH="~/.pyenv/bin:~/.pyenv/shims:~/Library/Python/3.6/bin:$PATH"
@@ -56,7 +65,7 @@ tar xz --directory $BUILDDIR
 cp $BUILDDIR/libusb/1.0.22/lib/libusb-1.0.dylib contrib/build-osx
 
 info "Building libsecp256k1"
-brew install autoconf automake libtool
+((uses_brew)) && brew install autoconf automake libtool
 git clone https://github.com/bitcoin-core/secp256k1 $BUILDDIR/secp256k1
 pushd $BUILDDIR/secp256k1
 git reset --hard $LIBSECP_VERSION
