Updated libsecp submodule commit pointer, fixup in scripts

diff --git a/contrib/make_secp b/contrib/make_secp
--- a/contrib/make_secp
+++ b/contrib/make_secp
@@ -2,6 +2,7 @@
 
 function fail {
     RED='\033[0;31m'
+    NC='\033[0m' # No Color
     printf "\r🗯 ${RED}ERROR:${NC} ${1}\n"
     exit 1
 }
@@ -16,12 +17,12 @@ git submodule init
 git submodule update
 
 echo "Building libsecp256k1..."
-LIBSECP_VERSION="a1d5a30364d2ca8ed8bb3ef3dd345cc75708a8b2"  # According to Mark B. Lundeberg, using a commit hash guarantees no repository man-in-the-middle funny business as git is secure when verifying hashes.
+LIBSECP_VERSION="9896f7062e67e05f9a1aa7163099fb2e052db9e8"  # According to Mark B. Lundeberg, using a commit hash guarantees no repository man-in-the-middle funny business as git is secure when verifying hashes.
 
 pushd "$contrib"/secp256k1 || fail "Could not chdir to ${contrib}/secp256k1"
 git checkout $LIBSECP_VERSION || fail "Could not check out secp256k1 $LIBSECP_VERSION"
 git clean -f -x -q
-./autogen.sh || fail "Could not run autogen for secp256k1"
+./autogen.sh || fail "Could not run autogen for secp256k1. Please make sure you have automake and libtool installed, and try again."
 ./configure \
     --enable-module-recovery \
     --enable-experimental \
@@ -31,7 +32,7 @@ git clean -f -x -q
     --enable-module-schnorr \
     --disable-tests \
     --disable-static \
-    --enable-shared || fail "Could not configure secp256k1"
+    --enable-shared || fail "Could not configure secp256k1. Please make sure you have a C compiler installed and try again."
 make -j4 || fail "Could not build secp256k1"
 uname=`uname -s`
 if [ "$uname" = "Darwin" ]; then
@@ -46,4 +47,4 @@ git checkout master  # Undo the previous explicit checkout to this hash
 git clean -f -x -q
 popd
 
-echo "libsecp256k1.0.so has been placed in the electroncash 'lib' folder."
+echo "$libsec_lib has been placed in the electroncash 'lib' folder."
