contrib scripts.. whereis -> which

diff --git a/contrib/make_secp b/contrib/make_secp
--- a/contrib/make_secp
+++ b/contrib/make_secp
@@ -9,7 +9,7 @@ function fail {
 contrib=$(dirname "$0")
 test -n "$contrib" -a -d "$contrib" || fail "Could not find the contrib/ directory"
 
-whereis git || fail "Git is required to proceed"
+which git || fail "Git is required to proceed"
 
 echo "Refreshing submodules..."
 git submodule init
@@ -47,4 +47,3 @@ git clean -f -x -q
 popd
 
 echo "libsecp256k1.0.so has been placed in the electroncash 'lib' folder."
-
