ren electrum->electrumsys

diff --git a/contrib/make_tgz b/contrib/make_tgz
--- a/contrib/make_tgz
+++ b/contrib/make_tgz
@@ -5,7 +5,7 @@ set -e
 CONTRIB="$(dirname "$(readlink -e "$0")")"
 ROOT_FOLDER="$CONTRIB"/..
 PACKAGES="$ROOT_FOLDER"/packages/
-LOCALE="$ROOT_FOLDER"/electrum/locale/
+LOCALE="$ROOT_FOLDER"/electrumsys/locale/
 
 if [ ! -d "$PACKAGES" ]; then
   echo "Run make_packages first!"
@@ -17,16 +17,16 @@ git submodule update --init
 "$CONTRIB"/make_libsecp256k1.sh || fail "Could not build libsecp"
 (
     rm -rf "$LOCALE"
-    cd "$CONTRIB/deterministic-build/electrum-locale/"
+    cd "$CONTRIB/deterministic-build/electrumsys-locale/"
     if ! which msgfmt > /dev/null 2>&1; then
         echo "Please install gettext"
         exit 1
     fi
     for i in ./locale/*; do
-        dir="$ROOT_FOLDER"/electrum/$i/LC_MESSAGES
+        dir="$ROOT_FOLDER"/electrumsys/$i/LC_MESSAGES
         mkdir -p $dir
-        msgfmt --output-file=$dir/electrum.mo $i/electrum.po || true
-        cp $i/electrum.po "$ROOT_FOLDER"/electrum/$i/electrum.po
+        msgfmt --output-file=$dir/electrumsys.mo $i/electrumsys.po || true
+        cp $i/electrumsys.po "$ROOT_FOLDER"/electrumsys/$i/electrumsys.po
     done
 )
 
@@ -38,7 +38,7 @@ git submodule update --init
     echo "<<<"
 
     # we could build the kivy atlas potentially?
-    #(cd electrum/gui/kivy/; make theming) || echo "building kivy atlas failed! skipping."
+    #(cd electrumsys/gui/kivy/; make theming) || echo "building kivy atlas failed! skipping."
 
     python3 setup.py --quiet sdist --format=zip,gztar
 )
diff --git a/contrib/osx/make_osx b/contrib/osx/make_osx
--- a/contrib/osx/make_osx
+++ b/contrib/osx/make_osx
@@ -2,9 +2,9 @@
 
 # Parameterize
 PYTHON_VERSION=3.7.6
-BUILDDIR=/tmp/electrum-build
+BUILDDIR=/tmp/electrumsys-build
 PACKAGE=ElectrumSys
-GIT_REPO=https://github.com/syscoin/electrum
+GIT_REPO=https://github.com/syscoin/electrumsys
 LIBSECP_VERSION="b408c6a8b287003d1ade5709e6f7bc3c7f1d5be7"
 
 export GCC_STRIP_BINARIES="1"
@@ -81,11 +81,11 @@ info "generating locale"
         brew install gettext
         brew link --force gettext
     fi
-    cd "$CONTRIB"/deterministic-build/electrum-locale
+    cd "$CONTRIB"/deterministic-build/electrumsys-locale
     for i in ./locale/*; do
-        dir="$ROOT_FOLDER"/electrum/$i/LC_MESSAGES
+        dir="$ROOT_FOLDER"/electrumsys/$i/LC_MESSAGES
         mkdir -p $dir
-        msgfmt --output-file=$dir/electrum.mo $i/electrum.po || true
+        msgfmt --output-file=$dir/electrumsys.mo $i/electrumsys.po || true
     done
 ) || fail "failed generating locale"
 
@@ -100,7 +100,7 @@ echo "82c368dfd4da017ceb32b12ca885576f325503428a4966cc09302cbd62702493  contrib/
 info "Preparing for building libsecp256k1"
 brew install autoconf automake libtool
 "$CONTRIB"/make_libsecp256k1.sh || fail "Could not build libsecp"
-cp "$ROOT_FOLDER"/electrum/libsecp256k1.0.dylib contrib/osx
+cp "$ROOT_FOLDER"/electrumsys/libsecp256k1.0.dylib contrib/osx
 
 info "Building CalinsQRReader..."
 d=contrib/osx/CalinsQRReader
@@ -142,9 +142,9 @@ plutil -insert 'CFBundleURLTypes' \
 DoCodeSignMaybe "app bundle" "dist/${PACKAGE}.app" "$APP_SIGN" # If APP_SIGN is empty will be a noop
 
 info "Creating .DMG"
-hdiutil create -fs HFS+ -volname $PACKAGE -srcfolder dist/$PACKAGE.app dist/electrum-$VERSION.dmg || fail "Could not create .DMG"
+hdiutil create -fs HFS+ -volname $PACKAGE -srcfolder dist/$PACKAGE.app dist/electrumsys-$VERSION.dmg || fail "Could not create .DMG"
 
-DoCodeSignMaybe ".DMG" "dist/electrum-${VERSION}.dmg" "$APP_SIGN" # If APP_SIGN is empty will be a noop
+DoCodeSignMaybe ".DMG" "dist/electrumsys-${VERSION}.dmg" "$APP_SIGN" # If APP_SIGN is empty will be a noop
 
 if [ -z "$APP_SIGN" ]; then
     warn "App was built successfully but was not code signed. Users may get security warnings from macOS."
