OSX Build: Fixed generated filename for El Capitan
Our convention for the legacy El Capitan build was the
-macosx-elcapitan.dmg (so that it sorts after the plain -macosx.dmg).

The build script had it reversed as -elcapitan-macos.dmg (and it sorted
first, making it more likely users would just download that one).

This has now been fixed.

diff --git a/contrib/osx/make_osx b/contrib/osx/make_osx
--- a/contrib/osx/make_osx
+++ b/contrib/osx/make_osx
@@ -249,9 +249,9 @@ DoCodeSignMaybe "app bundle" "dist/${PACKAGE}.app" "$APP_SIGN" # must force a co
 
 info "Creating .DMG"
 
-dmgbuild -D PACKAGE=$PACKAGE -s contrib/osx/dmgbuild.spec "" "dist/${PACKAGE}-${VERSION}${OSX_COMPAT}-macosx.dmg" || fail "Could not create .DMG"
+dmgbuild -D PACKAGE=$PACKAGE -s contrib/osx/dmgbuild.spec "" "dist/${PACKAGE}-${VERSION}-macosx${OSX_COMPAT}.dmg" || fail "Could not create .DMG"
 
-DoCodeSignMaybe ".DMG" "dist/${PACKAGE}-${VERSION}${OSX_COMPAT}-macosx.dmg" "$APP_SIGN" # If APP_SIGN is empty will be a noop
+DoCodeSignMaybe ".DMG" "dist/${PACKAGE}-${VERSION}$-macosx{OSX_COMPAT}.dmg" "$APP_SIGN" # If APP_SIGN is empty will be a noop
 
 if [ -z "$APP_SIGN" ]; then
     warn "App was built successfully but was not code signed. Users may get security warnings from macOS."
