[OSX] Make a fancy dmg (#1268)
* Added fancy dmg

* append -macosx to dmg file basename

* updated dmg_settings.py to be python3.5ish

* tweaks, improved background

diff --git a/contrib/osx/make_osx b/contrib/osx/make_osx
--- a/contrib/osx/make_osx
+++ b/contrib/osx/make_osx
@@ -99,6 +99,8 @@ git submodule update
 rm  -rf $BUILDDIR > /dev/null 2>&1
 mkdir $BUILDDIR
 
+info "Installing dmgbuild..."
+python3 -m pip install -I --user dmgbuild || fail "Could not install dmgbuild"
 info "Installing requests..."
 python3 -m pip install -I --user requests || fail "Could not install requests"
 info "Making locale..."
@@ -165,9 +167,9 @@ plutil -insert 'CFBundleURLTypes' \
 DoCodeSignMaybe "app bundle" "dist/${PACKAGE}.app" "$APP_SIGN" # must force a codesign again because Info.plist modified above
 
 info "Creating .DMG"
-hdiutil create -fs HFS+ -volname $PACKAGE -srcfolder dist/$PACKAGE.app dist/$PACKAGE-$VERSION.dmg || fail "Could not create .DMG"
+dmgbuild -D PACKAGE=$PACKAGE -s contrib/osx/dmg_settings.py "" dist/$PACKAGE-$VERSION-macosx.dmg || fail "Could not create .DMG"
 
-DoCodeSignMaybe ".DMG" "dist/${PACKAGE}-${VERSION}.dmg" "$APP_SIGN" # If APP_SIGN is empty will be a noop
+DoCodeSignMaybe ".DMG" "dist/${PACKAGE}-${VERSION}-macosx.dmg" "$APP_SIGN" # If APP_SIGN is empty will be a noop
 
 if [ -z "$APP_SIGN" ]; then
     warn "App was built successfully but was not code signed. Users may get security warnings from macOS."
