Revert MacOS build to PyQt5 5.11.x until Qt 5.13.1 is released.
The reason for this is because there are issues with PyQt5 5.12.x &
5.13.0. QPushButtons sometimes don't send click events (they get dropped
basically).  This has been fixed in 5.13.1 dev snapshot.

So, we revert to PyQt5 5.11.x which is less than ideal because:

Mojave doesn't work quite right on 5.11 (dark mode in particular is not
supported, as well as other misc. rendering quirks).  However, it's better
to use 5.11, with the Mojave caveats in mind, than 5.12 and 5.13.0 which
drop UI events if the main thread is busy.

We will re-enable Qt 5.13.x when PyQt5 5.13.1 is released (this works
much better on all platforms at the expense of dropping support for El
Capitan).

See Qt Bug:
http://bugreports.qt.io/browse/QTBUG-69687

Commit that fixes this:
https://code.qt.io/cgit/qt/qtbase.git/commit/?h=5.13.1&id=09a2a9bc4a4a5c9ef7849d3f30243cd8e2d389d1

diff --git a/contrib/osx/make_osx b/contrib/osx/make_osx
--- a/contrib/osx/make_osx
+++ b/contrib/osx/make_osx
@@ -6,15 +6,22 @@ test -n "$build_dir" -a -d "$build_dir" || (echo "Cannot determine build dir. FI
 . "$build_dir"/../base.sh # functions we use below
 
 OSX_COMPAT=""
-DARWIN_VER=$(uname -r | cut -f 1 -d .)
-if ((DARWIN_VER < 15)); then
-    fail "Minimum OSX El Capitan is required to build"
-elif ((DARWIN_VER == 15)); then
-    # If El Capitan, we use a different requirements-binaries file (for Qt 5.11)
-    # and we will produce a file with -elcapitan-macosx.dmg as a suffix.
-    OSX_COMPAT="-elcapitan"
-    info "Building for El Capitan (compatibility version)"
-fi
+# This mechanism has been disabled for now becasue Qt 5.12.x & Qt 5.13.0 have
+# some bugs still on all macOS (QPushButtons not always sending clicks through).
+# For now we use the requirements-binaries-elcapitan.txt always, which uses
+# PyQt5.11 (which works better on macOS before Mojave and not perfectly but
+# acceptably on Mojave).
+#DARWIN_VER=$(uname -r | cut -f 1 -d .)
+#if ((DARWIN_VER < 15)); then
+#    fail "Minimum OSX El Capitan is required to build"
+#elif ((DARWIN_VER == 15)); then
+#    # If El Capitan, we use a different requirements-binaries file (for Qt 5.11)
+#    # and we will produce a file with -elcapitan-macosx.dmg as a suffix.
+#    OSX_COMPAT="-elcapitan"
+#    info "Building for El Capitan (compatibility version)"
+#fi
+#REQUIREMENTS_BINARIES="requirements-binaries${OSX_COMPAT}.txt"
+REQUIREMENTS_BINARIES="requirements-binaries-elcapitan.txt"  # hard-coded for now, uses PyQt5.11
 
 function DoCodeSignMaybe { # ARGS: infoName fileOrDirName codesignIdentity
     infoName="$1"
@@ -168,9 +175,8 @@ popd
 cp -fp contrib/secp256k1/.libs/libsecp256k1.0.dylib contrib/osx || fail "Could not copy secp256k1 binary to its destination"
 
 info "Installing requirements..."
-python3 -m pip install -Ir ./contrib/deterministic-build/requirements.txt --user && \
-python3 -m pip install -Ir ./contrib/deterministic-build/requirements-binaries${OSX_COMPAT}.txt --user || \
-fail "Could not install requirements"
+python3 -m pip install -Ir ./contrib/deterministic-build/requirements.txt --user || fail "Could not install requirements"
+python3 -m pip install -Ir ./contrib/deterministic-build/${REQUIREMENTS_BINARIES} --user || fail "Could not install binary requirements"
 
 info "Installing hardware wallet requirements..."
 python3 -m pip install -Ir ./contrib/deterministic-build/requirements-hw.txt --user || \
