OSX: Fixups for Mojave visual & font glitches (#1580)
It turns out the way we've been building Electron Cash on El Capitan using PyQt 5.11 led to visual glitches on Mojave.  Some widgets didn't render quite right and font weights were too bold, among other minor problems.

Qt 5.12 is the first version of Qt to actually look good on Mojave.

But there is a problem with Qt 5.12 for compatibility: it no longer supports El Capitan.

As a result we do the following:

- Upgraded `make_osx` to use the same requirements file as the other platforms (which uses PyQt 5.12.3); this fixes the Mojave glitch problem
- *HOWEVER* 8-12% of macOS users are still on El Capitan and Qt 5.12 won't run on El Capitan, so we also support building on El Capitan systems for El Capitan. This will produce a `.dmg` with a `-elcapitan-macosx.dmg` suffix.
- As such, `make_osx` can auto-detect if it is being build on El Capitan and it will use an alternate `requirements-binaries.txt` file which uses PyQt 5.11.
- So, in summary: For a few releases we should release both the regular (built on Sierra, works on Mojave, uses Qt 5.12) `.dmg` as well as the `-elcapitan-macosx.dmg` (built on El Capitan, uses Qt 5.11, works flawlessly on everything up to Mojave).

Additionally, this commit provides a workaroud and a warning should the user run the `-elcapitan-macosx.dmg` on a Mojave system (but it still allows them to proceed).

This commit also slightly refactors `electroncash_gui/qt/__init__.py` to put some of the pre-App-setup initialization stuff into a separate method.

---

* MacOS: Mojave workaround for PyQt 5.11

We warn the user that PyQt 5.11 + Mojave is a bad time. We also try to
apply some hacky workarounds to mitigate some of the font rendering
issues with Qt 5.11 on Mojave.

* OSX: Fix to use alternate requirements-binaries for El Capitan builds

We use an alternate, PyQt 5.11 requirements-binaries for El Capitan
builds.

All other newer MacOS will use PyQt5.12.3.

* OSX: Nits to Mojave Qt5.11 fixup code

* make_osx: Added more pre-requisites for brew

* tweak to make_osx

diff --git a/contrib/osx/make_osx b/contrib/osx/make_osx
--- a/contrib/osx/make_osx
+++ b/contrib/osx/make_osx
@@ -5,6 +5,17 @@ test -n "$build_dir" -a -d "$build_dir" || (echo "Cannot determine build dir. FI
 
 . "$build_dir"/../base.sh # functions we use below
 
+OSX_COMPAT=""
+DARWIN_VER=$(uname -r | cut -f 1 -d .)
+if ((DARWIN_VER < 15)); then
+    fail "Minimum OSX El Capitan is required to build"
+elif ((DARWIN_VER == 15)); then
+    # If El Capitan, we use a different requirements-binaries file (for Qt 5.11)
+    # and we will produce a file with -elcapitan-macosx.dmg as a suffix.
+    OSX_COMPAT="-elcapitan"
+    info "Building for El Capitan (compatibility version)"
+fi
+
 function DoCodeSignMaybe { # ARGS: infoName fileOrDirName codesignIdentity
     infoName="$1"
     file="$2"
@@ -57,8 +68,8 @@ fi
 
 have_brew=`which brew`
 if [ -n "$have_brew" ]; then
-    info "Ensuring Python prerequisites are installed via brew"
-    for a in openssl@1.1 readline sqlite3 xz zlib coreutils; do
+    info "Ensuring build prerequisites are installed via brew"
+    for a in autoconf automake coreutils gettext libtool openssl@1.1 readline sqlite3 xz zlib ; do
         brew list $a > /dev/null 2>&1
         if [ "$?" != "0" ]; then
             info "Installing $a"
@@ -158,7 +169,7 @@ cp -fp contrib/secp256k1/.libs/libsecp256k1.0.dylib contrib/osx || fail "Could n
 
 info "Installing requirements..."
 python3 -m pip install -Ir ./contrib/deterministic-build/requirements.txt --user && \
-python3 -m pip install -Ir ./contrib/deterministic-build/requirements-binaries-osx.txt --user || \
+python3 -m pip install -Ir ./contrib/deterministic-build/requirements-binaries${OSX_COMPAT}.txt --user || \
 fail "Could not install requirements"
 
 info "Installing hardware wallet requirements..."
@@ -199,9 +210,10 @@ plutil -insert 'CFBundleURLTypes' \
 DoCodeSignMaybe "app bundle" "dist/${PACKAGE}.app" "$APP_SIGN" # must force a codesign again because Info.plist modified above
 
 info "Creating .DMG"
-dmgbuild -D PACKAGE=$PACKAGE -s contrib/osx/dmgbuild.spec "" dist/$PACKAGE-$VERSION-macosx.dmg || fail "Could not create .DMG"
 
-DoCodeSignMaybe ".DMG" "dist/${PACKAGE}-${VERSION}-macosx.dmg" "$APP_SIGN" # If APP_SIGN is empty will be a noop
+dmgbuild -D PACKAGE=$PACKAGE -s contrib/osx/dmgbuild.spec "" "dist/${PACKAGE}-${VERSION}${OSX_COMPAT}-macosx.dmg" || fail "Could not create .DMG"
+
+DoCodeSignMaybe ".DMG" "dist/${PACKAGE}-${VERSION}${OSX_COMPAT}-macosx.dmg" "$APP_SIGN" # If APP_SIGN is empty will be a noop
 
 if [ -z "$APP_SIGN" ]; then
     warn "App was built successfully but was not code signed. Users may get security warnings from macOS."
