[OSX] Switched PyInstaller to our patched AppleEvents+CodeSign version
Patched PyInstaller is identical to 3.4 release except it has the
following additional features:

- Allows for AppleEvents to get forwarded to Electrum slave process
(python interpreter).  This means bitcoin: URLs work even AFTER the app
is already running (at present they do not).

- Has the addition of the command-line option --osx-codesign-identity
with allows for code signing of *all* embedded binaries and libs as the
.app is built. The PR to PyInstaller has been submitted here:
https://github.com/pyinstaller/pyinstaller/pull/3991 but has not yet
beed accepted

This commit also undoes the monkey patching of pyinstaller to achieve #2
above and is much cleaner for maintainers.

Note: I am currently hosting the custom PyIntstaller.zip on my repo
here:
https://github.com/cculianu/pyinstaller/releases/tag/3.4AppleEventsCodeSign
but feel free to fork/copy this repo under the ecdsa or spesmilo
account.

diff --git a/contrib/osx/make_osx b/contrib/osx/make_osx
--- a/contrib/osx/make_osx
+++ b/contrib/osx/make_osx
@@ -48,8 +48,8 @@ pyenv global $PYTHON_VERSION || \
 fail "Unable to use Python $PYTHON_VERSION"
 
 
-info "Installing pyinstaller"
-python3 -m pip install -I --user pyinstaller==3.4 || fail "Could not install pyinstaller"
+info "Installing PyInstaller"
+python3 -m pip install https://github.com/cculianu/pyinstaller/releases/download/3.4AppleEventsCodeSign/PyInstaller_3.4+AppleEvents+CodeSign.zip -I --user && pyenv rehash || fail "Could not install PyInstaller"
 
 info "Using these versions for building $PACKAGE:"
 sw_vers
@@ -118,7 +118,11 @@ for d in ~/Library/Python/ ~/.pyenv .; do
 done
 
 info "Building binary"
-APP_SIGN="$APP_SIGN" pyinstaller --noconfirm --ascii --clean --name $VERSION contrib/osx/osx.spec || fail "Could not build binary"
+if [ -n "$APP_SIGN" ]; then
+    pyinstaller --osx-codesign-identity "$APP_SIGN" --noconfirm --ascii --clean --name $VERSION contrib/osx/osx.spec || fail "Could not build binary"
+else
+    pyinstaller --noconfirm --ascii --clean --name $VERSION contrib/osx/osx.spec || fail "Could not build binary"
+fi
 
 info "Adding bitcoin URI types to Info.plist"
 plutil -insert 'CFBundleURLTypes' \
@@ -126,7 +130,7 @@ plutil -insert 'CFBundleURLTypes' \
 	-- dist/$PACKAGE.app/Contents/Info.plist \
 	|| fail "Could not add keys to Info.plist. Make sure the program 'plutil' exists and is installed."
 
-DoCodeSignMaybe "app bundle" "dist/${PACKAGE}.app" "$APP_SIGN" # If APP_SIGN is empty will be a noop
+DoCodeSignMaybe "app bundle" "dist/${PACKAGE}.app" "$APP_SIGN" # must force a codesign again because Info.plist modified above
 
 info "Creating .DMG"
 hdiutil create -fs HFS+ -volname $PACKAGE -srcfolder dist/$PACKAGE.app dist/electrum-$VERSION.dmg || fail "Could not create .DMG"
