OSX Fixups and improvements for dark mode and more
Squashed commit of the following:

commit 5f84a329ced22a846009bbe319963cadd36dd124
Author: Calin Culianu <calin.culianu@gmail.com>
Date:   Sun May 24 20:30:37 2020 +0300

    OSX: Fixups for Mojave+ dark mode

    - We added a facility in qt/utils called "Dark Detect" which detects
    dark mode reliably on macOS (Mojave+ only).  The fallback is the old
    way.

    - Updated About dialog Copyright notice to conform with darkdetect BSD 3
    clause license.

    - qt.util.ColorScheme has been modified to use this darkdetect facility if
    available when querying ColorScheme.dark_scheme.  If not macOS or macOS
    less than Mojave, then we do the old way of just relying on the boolean value
    set at app startup.

    - Some misc. fixups for PayToEdit and other of the ButtonTextEdits that
    had bad alignment/layout on macos with dark mode.

commit dc4c44140851e1b5ef49077e809343053eeea5de
Author: Calin Culianu <calin.culianu@gmail.com>
Date:   Sun May 24 17:46:48 2020 +0300

    OSX Fix: added camera permissions to entitlements.plist

    Otherwise the app crashes when it attempts to access the camera on some
    systems.  This fixes that.  Apple is so draconian.

commit 46940a94cca743d52e13ccd94c08539059faddee
Author: Calin Culianu <calin.culianu@gmail.com>
Date:   Sun May 24 16:42:43 2020 +0300

    OSX: Added Info.plist key for Camera access

commit 1839ca2e2654c45b310f272b36d5ab0968b806c0
Author: Calin Culianu <calin.culianu@gmail.com>
Date:   Sun May 24 16:30:01 2020 +0300

    OSX: Disable dark theme, advise user to use Mojave panel instead

    Dark theme is broken on OSX because the maintainers really are focusing
    more on Linux.  As such, we simply advise the user to get the superior
    dark theme provided by the OS itself.

commit 2bb2918d014a9e3e1ac2b051fb960bf1d573d43d
Author: Calin Culianu <calin.culianu@gmail.com>
Date:   Sun May 24 16:06:00 2020 +0300

    OSX build: Updated PyQt5 version to 5.14.2

    This requires us to use a custom requirements-binaries-osx.txt for
    Darwin because we haven't yet fully tested 5.14.2 on all platforms, but
    on MacOS at least this version of PyQt5 is superior, so we opted to use
    it.

commit c88cb63359325fd660249abbdb1f4c737472396d
Author: Calin Culianu <calin.culianu@gmail.com>
Date:   Sun May 24 15:36:22 2020 +0300

    Updated OSX build script to use latest PyInstaller 3.6 + AppleEvents

    I updated my patch to work on 3.6 PyInstaller.  Latest PyInstaller is
    required to be able to build apps with the latest Qt 5.14+.

    Note we no longer do deep codesigning.  It is not very helpful anyway to
    do it, so we don't bother.

diff --git a/contrib/osx/make_osx b/contrib/osx/make_osx
--- a/contrib/osx/make_osx
+++ b/contrib/osx/make_osx
@@ -6,6 +6,7 @@ test -n "$build_dir" -a -d "$build_dir" || (echo "Cannot determine build dir. FI
 . "$build_dir"/../base.sh # functions we use below
 
 OSX_COMPAT=""
+OSX_REQ_BIN="-osx"
 DARWIN_VER=$(uname -r | cut -f 1 -d .)
 if ((DARWIN_VER < 15)); then
     fail "Minimum OSX El Capitan is required to build"
@@ -13,9 +14,10 @@ elif ((DARWIN_VER == 15)); then
     # If El Capitan, we use a different requirements-binaries file (for Qt 5.11)
     # and we will produce a file with -elcapitan-macosx.dmg as a suffix.
     OSX_COMPAT="-elcapitan"
+    OSX_REQ_BIN="$OSX_COMPAT"
     info "Building for El Capitan (compatibility version)"
 fi
-REQUIREMENTS_BINARIES="requirements-binaries${OSX_COMPAT}.txt"
+REQUIREMENTS_BINARIES="requirements-binaries${OSX_REQ_BIN}.txt"
 
 function DoCodeSignMaybe { # ARGS: infoName fileOrDirName codesignIdentity
     infoName="$1"
@@ -136,13 +138,13 @@ python3 -m pip install $BUILDDIR/$PYSCARD_FNAME --user && pyenv rehash \
 info "Installing PyInstaller"
 USE_CUSTOM_PYINSTALLER=1
 if ((USE_CUSTOM_PYINSTALLER)); then
-    # We use a custom PyInstaller that has deep codesigning as well as AppleEvents
-    # forwarding.  Note both these patches have been submitted to the PyInstaller
-    # project but have yet to be merged in (they are very backlogged).
+    # We use a custom PyInstaller that has AppleEvents forwarding. Note this
+    # patch has been submitted to the PyInstaller project but has yet to be
+    # merged-in (they are very backlogged).
     mkdir -p $BUILDDIR
-    curl -L https://github.com/cculianu/pyinstaller/releases/download/3.4AppleEventsCodeSign/PyInstaller_3.4+AppleEvents+CodeSign.zip > $BUILDDIR/PyInstaller34_AECS.zip
-    verify_hash $BUILDDIR/PyInstaller34_AECS.zip 543b2d98847f99df45d23e344c85acf3bfc5c057c95c09f444fd1b6b2cae749c
-    python3 -m pip install $BUILDDIR/PyInstaller34_AECS.zip --user --upgrade && pyenv rehash \
+    curl -L https://github.com/cculianu/pyinstaller/releases/download/v3.6_AE_Release_1/PyInstaller36_AppleEvents.zip > $BUILDDIR/PyInstaller36_AppleEvents.zip
+    verify_hash $BUILDDIR/PyInstaller36_AppleEvents.zip 0b2865c6e788abf26717a1c72f0164cba34d10836b9263a4e777a19ee8a79a2c
+    python3 -m pip install $BUILDDIR/PyInstaller36_AppleEvents.zip --user --upgrade && pyenv rehash \
         || fail "Could not install PyInstaller"
 else
     # Just use regular, latest PyInstaller 3.6+
@@ -209,12 +211,7 @@ info "Building $PACKAGE..."
 python3 setup.py install --user > /dev/null || fail "Could not build $PACKAGE"
 
 info "Building binary"
-DEEP_SIGN=1  # Set to 1 if we want to codesign all the embedded binaries (requires our custom pyinstaller)
-if [ -n "$APP_SIGN" ] && ((USE_CUSTOM_PYINSTALLER)) && ((DEEP_SIGN)); then
-    pyinstaller --osx-codesign-identity "$APP_SIGN" --clean --noconfirm --ascii --name $VERSION contrib/osx/osx.spec || fail "Could not build binary"
-else
-    pyinstaller --clean --noconfirm --ascii --name $VERSION contrib/osx/osx.spec || fail "Could not build binary"
-fi
+pyinstaller --clean --noconfirm --ascii --name $VERSION contrib/osx/osx.spec || fail "Could not build binary"
 
 info "Adding bitcoincash & cashacct URI types to Info.plist"
 # NB: Make sure there are no trailing spaces after the '\' characters here
@@ -236,6 +233,12 @@ plutil -insert 'CFBundleURLTypes' \
 '</array>' \
 	-- dist/$PACKAGE.app/Contents/Info.plist \
 	|| fail "Could not add keys to Info.plist. Make sure the program 'plutil' exists and is installed."
+
+plutil -insert 'NSCameraUsageDescription' \
+       -string 'Electron Cash would like to access the camera to scan for QR codes' \
+	-- dist/$PACKAGE.app/Contents/Info.plist \
+	|| fail "Could not add keys to Info.plist. Make sure the program 'plutil' exists and is installed."
+
 
 FORCE_MOJAVE_DARK=0  # Set to 1 to try and add the Info.plist key to force mojave dark mode supprt. As of PyQt 5.14.1, it doesn't work.
 if ((DARWIN_VER >= 18 && FORCE_MOJAVE_DARK)); then
